[settings]
name = "Foobar"
package_name = "example" # go package of generated file

[vars.PGUsername]
var = "FOOBAR_PG_USERNAME" # Environment variable key used
type = "string"
default = "postgres"

[vars.PGPassword]
var = "FOOBAR_PG_PASSWORD"
type = "string"
optional = true

[vars.Environment]
var = "FOOBAR_DEPLOY_ENV"
type = "enum"                          # enum types require a list of string values
enum_values = ["local", "dev", "prod"]

[vars.EnableSomething]
var = "FOOBAR_ENABLE_SOMETHING"
type = "bool"

[vars.MaxConnections]
var = "FOOBAR_MAX_CONNECTIONS"
type = "int64"
default = "256 * 256"
